import { z } from "zod";

export const userSchema = z.object({
  id: z.uuid().optional(), // generated by default
  firstname: z.string().min(1).max(55),
  lastname: z.string().max(55).optional(),
  email: z.string().email().max(255),
  password: z.string().min(8), // you might want stronger rules here
  salt: z.string(),
  createdAt: z.date().optional(), // defaultNow() handled by DB
  updatedAt: z.date().optional(),
  deletedAt: z.date().optional(),
});
export const createUserSchema = userSchema.omit({
  id:true,salt:true,createdAt:true,updatedAt:true,deletedAt:true
})
// Types inferred from Zod
export type UserInput = z.infer<typeof createUserSchema>;
